// <auto-generated />
namespace bizzart_proj.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class new_migr : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(new_migr));
        
        string IMigrationMetadata.Id
        {
            get { return "201903290320095_new_migr"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
